export const BoombData = [
  {
    position: 1,
    rotate: "rotateY(0deg)",
    img: "",
    defaultRotate: 670,
    editCrop: "1",
    height: 0,
    width: 0,
    sideName: "Front",
  },
  {
    position: 2,
    rotate: "rotateY(90deg)",
    img: "",
    defaultRotate: 580,
    editCrop: "1",
    height: 0,
    width: 0,
    sideName: "Left",
  },
  {
    position: 3,
    rotate: "rotateY(180deg)",
    img: "",
    defaultRotate: 490,
    editCrop: "1",
    height: 0,
    width: 0,
    sideName: "Back",
  },
  {
    position: 4,
    rotate: "rotateY(-90deg)",
    img: "",
    defaultRotate: 760,
    editCrop: "1",
    height: 0,
    width: 0,
    sideName: "Right",
  },
];
