export const SET_BOOMB = 'SET_BOOMB'
export const SET_TOP_TEXT = 'SET_TOP_TEXT'
export const EDIT_IMAGE = 'EDIT_IMAGE'
export const CURRENT_CUBE_POSITION = 'CURRENT_CUBE_POSITION'
export const CURRENT_CUBE_IMAGE = 'CURRENT_CUBE_IMAGE'

export const SEND_BOOMB = 'SEND_BOOMB'

