export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const GET_BOOMF_LIBRARY_CATEGORIES = "GET_BOOMF_LIBRARY_CATEGORIES";
export const SET_IMAGES_CATEGORIES = "SET_IMAGES_CATEGORIES";
export const GET_BOOMF_LIBRARY_IMAGES = "GET_BOOMF_LIBRARY_IMAGES";
export const SET_IMAGES = "SET_IMAGES";
export const SET_PRODUCT_TYPE = "SET_PRODUCT_TYPE";
export const GET_USER_IMAGES = "GET_USER_IMAGES";
export const FILTER_IMAGES = "FILTER_IMAGES";
