export const SET_IMAGE_LIBRARY = 'SET_IMAGE_LIBRARY';
export const SET_IMAGE_LIBRARY_DATA = 'SET_IMAGE_LIBRARY_DATA';
export const SET_ADD_IMAGE_LIBRARY = 'SET_ADD_IMAGE_LIBRARY';
export const SET_UPDATE_IMAGE_LIBRARY = 'SET_UPDATE_IMAGE_LIBRARY';
export const SET_DELETE_IMAGE_LIBRARY = 'SET_DELETE_IMAGE_LIBRARY';