export const SET_ACTIVE_TEXT_DATA = 'SET_ACTIVE_TEXT_DATA';
export const SET_DATA_TEXT = 'SET_DATA_TEXT';
export const SET_ADD_TEXT_DATA = 'SET_ADD_TEXT_DATA';
export const SET_UPDATE_TEXT_DATA = 'SET_UPDATE_TEXT_DATA';
export const SET_DELETE_TEXT_DATA = 'SET_DELETE_TEXT_DATA';